[build]
publish = "site"
command = "python3 -m pip install --upgrade pip && pip3 install -r docs/requirements.txt && mkdocs build -d site -v"


[build.environment]
PIP_CACHE_DIR = ".cache/pip"
PYTHON_VERSION = "3.12"

[[plugins]]
package = "@netlify/plugin-cache"
[plugins.inputs]
paths = [".cache/pip"]
